### PR TITLE
errorhandler improvements: infinite loop due to successful preAction

### PR DESCRIPTION
**Pull request by DevD-official**
# Proposed changes
- removed attribute repeater from Executor class.
- handler.actions will not return repeater object as its available as its attribute.
- handler.actions does not return repeater as its available as its attribute.
- By default repeater is None; only during handler.actions repeater instance will be created if it is None.
- Added method is_exhausted() in class Repeater.
- If counter value of the repeater has been exhausted; preActions will not be queued in the stack.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by DevD-official** [comment]
Please review the changes.

**Comment by christoph2** [comment]
Unfortunatly there is a [merge conflict](https://github.com/christoph2/pyxcp/pull/123/conflicts) - In the current working version I had removed  *self.newHandler* and *self.repeater*, both attributes are apparently not required.

**Comment by DevD-official** [comment]
Thanks for the update. I tried the latest changes from the master. They are solving the infinite loop problem resulting from positive preAction. With minimal changes 😃 . My merge request can be rejected.

**Comment by DevD-official** [comment]
Closing.

**Pull request closed without merging**
