### PR TITLE
exposes the timeout option for the transport layer

### PR DESCRIPTION
**Pull request by danielhrisca**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

This PR exposes the timeout option for the transport layer. 

Especially when working in debug mode, the message processing (hex formatting etc.) can slow down the processing of incoming data to the point were the default 2s timeout is reached.

A new private flag for debug mode is needed for the same reason that formatting the incoming messages is expensive. I've also added the logging of the first 8 bytes of the ODT packets since this can give important information in case of wrong time stamps send by the XCP slave.

### CODE REVIEW

**Comment by christoph2** [comment]
Nice 

Soon there will be a faster way to trace/debug XCP traffic available: my forthcoming project includes a tool called *xcpdump* (SocketCAN only),  similar to *candump* and also written in C.

**Comment by danielhrisca** [comment]
I did some timings comparing Stream Handler to RotatingFileHandler while logging 80 characters long messages. The Stream Handler takes 500us per message and the RotatingFileHandler takes 60us.
For high data rate XCP slaves using the Stream Handler is a big bottleneck

**Comment by christoph2** [comment]
Doesn't PythonCAN include some logging options that could be (ab)used?

**Comment by danielhrisca** [comment]
I am using ethernet and USB XCP slaves so I can only use the pure python logging

**Pull request merged**
