### PR TITLE
add pyusb to pyproject.toml

### PR DESCRIPTION
**Pull request by felixn**
Adding pyusb to pyproject.toml allows for installation with pip.
This should also fix the issue with ReadTheDocs.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by christoph2** [comment]
Felix,  great to hear from you again :)

**Comment by danielhrisca** [comment]
Hello everybody,  does it make sense to do a version bump and push to PyPI?

**Comment by christoph2** [comment]
Absolutely,  I'm sure this is the problem. 
OK,  just bumped'n'pushed let's see...

**Comment by christoph2** [comment]
P. S. : I'm currently working hard on a high-speed DAQ logger which will be part of asamint,  maybe there will be even today an initial version...

**Comment by danielhrisca** [comment]
> P. S. : I'm currently working hard on a high-speed DAQ logger which will be part of asamint, maybe there will be even today an initial version...

What is the data rate that you see in your tests?

**Comment by christoph2** [comment]
Many thanks Felix,  I could never figure out how to make PyPI upload work...

**Comment by christoph2** [comment]
That's a good question, I haven't benched it yet,  what I do is as follows:
- Collect an arbitrary number of DAQ frames and than hand it over to another process using multiprocessing. 
- the other process in turn collects a certain amount of bytes and than comprresses it using LZ4.
- data is written on the fly using a memory-mapped sparse file.

**Comment by christoph2** [comment]
I've just added the file handling:
https://github.com/christoph2/asamint/blob/master/asamint/xcp/reco.py
Infrastructure and example stuff still missing.

**Comment by danielhrisca** [comment]
We do something similar in our internal application:
* Collect an arbitrary number of DAQ frames and than hand it over to another process using multiprocessing: interesting to see your approach for inter-process coordination 
* the other process in turn collects a certain amount of bytes and than comprresses it using LZ4: we need to use zlib since this is the only accepted compression method for MDF and it is a lot slower than LZ4. Do you do data transposition before compression (to get consecutive bytes for the same daq entries that might not change so much during the acquisition and thus improve the compression ratio)?
* data is written on the fly using a memory-mapped sparse file: is this just a compressed stream of bytes or some other file format?

**Comment by christoph2** [comment]
No,  I don't do any preprocessing of data. 
While LZ4 supports steaming,  I decided to use a proprietary block based file format.

**Comment by felixn** [comment]
> Felix, great to hear from you again :)

Thanks :D

> Many thanks Felix, I could never figure out how to make PyPI upload work...

The whole build automation, packaging and co is a complicated topic...
Now we only (attempt) to push to PyPI if the secrets are available, and installing from pip is working - so that's a step in the right direction.
But if I understand correctly, we still push to PyPI with every commit on trunk.
This means we potentially upload several different versions with the same version number (because that's only changed by hand).
Looking around, one option would be to push to PyPI only from tagged commits, like so:
`if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')`
(from https://github.com/pypa/gh-action-pypi-publish)
What do you think?

**Pull request merged**
