### PR TITLE
move some embedded enums to own types

### PR DESCRIPTION
**Pull request by felixn**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by christoph2** [comment]
Awesome Felix,  and btw.  it 's saturday morning. :smile:
P. S. :  I'm just working on the byte-order issue.

**Comment by danielhrisca** [comment]
Both of tou are doing a great job! Thank you!

**Comment by christoph2** [comment]
Awesome Felix,  and btw.  it 's saturday morning. :smile:
P. S. :  I'm just working on the byte-order issue.

**Comment by felixn** [comment]
Same to you, Christoph and Daniel!
I like the quick progress and the constructive cooperation with open and honest discussion in this project!

Christoph, if you want I can cook up some testcases for the byte-order issue.

**Comment by waszil** [comment]
Thanks guys, you are great!

**Pull request merged**
